Testing
YunoHost-Apps/pihole_ynh pull request #91
Opened 2022-10-18 20:38 UTC by ericgaspar

- Upgrade to 5.13

2022-10-18 20:39 UTC, ericgaspar commented
!testme

2022-10-19 10:54 UTC, ericgaspar commented
!testme

2022-10-19 19:21 UTC, yalh76 requested changes

2022-10-19 19:21 UTC, yalh76 commented on check_process
> +        upgrade=1   from_commit=4999654987af8b1427a6c72f8af482b235bb46db
You should keep test from  cfa9c5a3dbcfb765dcca3b2e7d179756afe26def and from 3d2f68c4e19f335e63f8ffa259708b38a58c8f67
and add a test from 4999654987af8b1427a6c72f8af482b235bb46db to be named 5.11.4~ynh2
There was a lot of modifications on those version

2022-10-19 20:32 UTC, ericgaspar commented
!testme

2022-10-19 20:35 UTC, yalh76 approved these changes

2022-10-20 06:03 UTC, merged